# This is a basic workflow to help you get started with Actions

name: publish-docs

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup environment
        run: |
          sudo apt-get install sbcl
          curl -O https://beta.quicklisp.org/quicklisp.lisp
          curl -O https://beta.quicklisp.org/quicklisp.lisp.asc
          sbcl \
            --non-interactive \
            --load quicklisp.lisp \
            --eval '(quicklisp-quickstart:install)' \
            --eval '
              (let ((ql-util::*do-not-prompt* t))
                (ql:add-to-init-file)
                (sb-ext:quit))
            '

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Copy project to quicklisp local-projects
        run: |
          cp -r ../${{ github.event.repository.name }} ~/quicklisp/local-projects

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Build docs
        run: |
          sbcl \
            --non-interactive \
            --eval '(ql:quickload :staple)' \
            --eval '(ql:quickload :vk)' \
            --eval '
              (progn
                (staple:generate :vk)
                (sb-ext:quit))
            '
          cat ~/quicklisp/local-projects/vk/docs/index.html
