# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # allegro: roswell installs 32bit version
        # clisp: can't be installed via roswell
        # cmucl: can't load cffi
        lisp: [sbcl-bin, abcl, ecl, ccl]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Install Vulkan
        run: |
          # Add lunarg apt sources
          wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-focal.list https://packages.lunarg.com/vulkan/lunarg-vulkan-focal.list
          
          # Update package lists
          sudo apt-get update -qq
          
          # Install dependencies
          sudo apt-get install -y \
            vulkan-sdk

      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/v20.06.14.107/scripts/install-for-ci.sh | sh
          
      - name: Install Rove
        run: ros install rove

      - name: Run tests
        run: |
          PATH="~/.roswell/bin:$PATH"
          rove vk.asd
