# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # allegro: roswell installs 32bit version
        # clisp: can't be installed via roswell
        # cmucl: can't load cffi (which is strange because that wasn't a problem before)
        lisp: [sbcl-bin, abcl, ecl, ccl]
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Setup (Linux)
        if: matrix.os == 'ubuntu-latest'
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          ### Install Vulkan SDK
          # Add lunarg apt sources
          wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-focal.list https://packages.lunarg.com/vulkan/lunarg-vulkan-focal.list
          
          # Update package lists
          sudo apt-get update -qq
          
          # Install dependencies
          sudo apt-get install -y \
            vulkan-sdk
          
          ### Install Roswell
          curl -L https://raw.githubusercontent.com/roswell/roswell/v20.06.14.107/scripts/install-for-ci.sh | sh
          
          ### Install Rove
          ros install rove

      - name: Setup (Windows) - Install Vulkan
        if: matrix.os == 'windows-latest'
        env:
          LISP: ${{ matrix.lisp }}
          ROSWELL_INSTALL_DIR: /c/roswell
        shell: pwsh
        run: |
          ### Install Vulkan SDK
          curl -LS -o vulkan-sdk.exe https://sdk.lunarg.com/sdk/download/latest/windows/VulkanSDK-Installer.exe
          7z x vulkan-sdk.exe -o"$GITHUB_WORKSPACE/vulkan_sdk/"

          ### Install Roswell
          PATH="/c/roswell/bin:$PATH"
          curl -L https://raw.githubusercontent.com/fukamachi/roswell/windows-source-registry-settings/scripts/install-for-ci.sh | sh
          
          ### Install Rove
          /c/roswell/bin/ros install rove

      - name: Run tests (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          PATH="~/.roswell/bin:$PATH"
          rove vk.asd

      - name: Run tests (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          PATH="~/.roswell/bin:/c/roswell/bin:$PATH"
          rove vk.asd
